name: Rhinestone-indexer
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"

rollback_on_reorg: false
# ------------------- Contracts configurations ---------------------
# ------------------------------------------------------------------

contracts:
  - name: Registry
    handler: src/handlers/Registry.ts
    events:
      - event: Attested(address indexed moduleAddress, address indexed attester, bytes32 schemaUID, address indexed sstore2Pointer)
      - event: ModuleRegistration(address indexed implementation)
      - event: Revoked(address indexed moduleAddress, address indexed revoker, bytes32 schema)

  - name: ColdStorageHook
    handler: src/handlers/ColdStorage.ts
    events:
      - event: TimelockExecuted(address indexed subAccount, bytes32 hash)
      - event: TimelockRequested(address indexed subAccount, bytes32 hash, uint256 executeAfter)

  - name: ScheduledOrders
    handler: src/handlers/ScheduledOrders.ts
    events:
      - event: ExecutionAdded(address indexed smartAccount, uint256 indexed jobId)
      - event: ExecutionTriggered(address indexed smartAccount, uint256 indexed jobId)
      - event: ExecutionsCancelled(address indexed smartAccount)

  - name: ScheduledTransfers
    handler: src/handlers/ScheduledTransfers.ts
    events:
      - event: ExecutionAdded(address indexed smartAccount, uint256 indexed jobId)
      - event: ExecutionTriggered(address indexed smartAccount, uint256 indexed jobId)
      - event: ExecutionsCancelled(address indexed smartAccount)

  - name: AutoSavings
    handler: src/handlers/AutoSavings.ts
    events:
      - event: AutoSaveExecuted(address indexed smartAccount, address indexed token, uint256 amountReceived)

  - name: SmartAccount
    handler: src/handlers/SmartAccount.ts
    events:
      - event: ModuleInstalled(uint256 moduleTypeId, address module)
      - event: ModuleUninstalled(uint256 moduleTypeId, address module)

unordered_multichain_mode: true

# ------------------- Network configurations ---------------------
# ----------------------------------------------------------------

networks:
  # Optimism ------------
  # ---------------------
  - id: 10
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # Polygon -------------
  # ---------------------
  - id: 137
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # Arbitrum ------------
  # ---------------------
  - id: 42161
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # Base ---------------
  # --------------------
  - id: 8453
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # Avalanche ---------------
  # --------------------
  - id: 43114
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # Gnosis ---------------
  # --------------------
  - id: 100
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # BSC ---------------
  # --------------------
  - id: 56
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # Sepolia ------------
  # --------------------
  - id: 11155111
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount

  # Base Sepolia ------------
  # --------------------
  - id: 84532
    start_block: 0
    contracts:
      - name: Registry
        address:
          - "0x0000000000E23E0033C3e93D9D4eBc2FF2AB2AEF"
      - name: ColdStorageHook
        address:
          - "0x7E31543b269632ddc55a23553f902f84C9DD8454"
      - name: ScheduledOrders
        address:
          - "0x40dc90D670C89F322fa8b9f685770296428DCb6b"
      - name: ScheduledTransfers
        address:
          - "0xA8E374779aeE60413c974b484d6509c7E4DDb6bA"
      - name: AutoSavings
        address:
          - "0x6AE48bD83B6bdc8489584Ea0814086f963d1BD95"
      - name: SmartAccount
